default_language_version:
  python: python3.12
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      args: ["--config=tox.ini", "--tee"]
