version: '3.8'

services:
  pastebin:
    build: .
    container_name: pastebin-app
    ports:
      - "8050:8050"
    volumes:
      - pastebin_pastes:/app/pastes
      - pastebin_secrets:/app/secrets
    environment:
      - PASTEBIN_DATA_DIR=/app/pastes
      - PASTEBIN_SECRETS_DIR=/app/secrets
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pastebin-network

networks:
  pastebin-network:
    driver: bridge

volumes:
  pastebin_pastes:
    driver: local
  pastebin_secrets:
    driver: local
