#!/bin/bash

set -e

BASE_URL=<<<base url>>>
PASTE_URL="${BASE_URL}/api/v1/paste"

check_dep() {
    printf "checking for %s... " "$1"
    if eval "$2" >/dev/null 2>&1; then
        echo "ok"
    else
        echo "missing"
        echo "Command failed: $2"
        echo "$3"
        exit 1
    fi
}

check_dep "python3" "python3 --version" "Install python3 with: sudo apt install python3"
check_dep "fernet" "python3 -c 'from cryptography.fernet import Fernet'" "Install fernet with: pip install cryptography"

PYTHON_SCRIPT='import sys, requests
from cryptography.fernet import Fernet
PASTE_URL = "'"${PASTE_URL}"'"

def main():
    key = Fernet.generate_key()
    cipher = Fernet(key)

    data = sys.stdin.buffer.read()
    encrypted = cipher.encrypt(data)

    r = requests.post(f"{PASTE_URL}", data=encrypted)
    if r.status_code != 201:
        sys.stderr.write(f"Upload failed: {r.status_code} {r.text}\n")
        sys.exit(1)

    paste_id = r.text.strip()
    print(f"{PASTE_URL}/{paste_id}#{key.decode()}")

if __name__ == "__main__":
    main()'

TMPFILE=$(mktemp)
echo "Enter paste content (Ctrl+D to finish):"
cat < /dev/tty > "$TMPFILE"

echo "--------------------------------"

echo "Paste secret URL:"
echo ""

python3 -c "$PYTHON_SCRIPT" < "$TMPFILE"
rm -f "$TMPFILE"

echo ""
echo "--------------------------------"

echo "If you open this URL in your browser, you will see the encrypted paste content."
echo "The encryption key was generated by the script and is not stored anywhere."
echo "To decrypt the paste content, run the following command:"
echo "    curl -s $BASE_URL/pull.sh | bash"
echo "It will prompt you to paste the secret URL to decrypt the paste content."
echo "--------------------------------"
